name: DuelsPro
version: 1.0
main: me.streafe.DuelsPro.DuelsPro
description: DuelsPro plugin

commands:
  PlayerList:
    usage: /<command>
    description: Get the registered users online
    default: op
  ban:
    usage: /<command>
    description: Ban player
    default: op
  unban:
    usage: /<command>
    description: Unban player
    default: op